# Generated by Django 5.0.2 on 2024-02-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=255)),
                ('pemilik', models.CharField(max_length=255)),
                ('tahun_berdiri', models.CharField(max_length=255)),
                ('jenis_toko', models.CharField(choices=[('MENJUAL JASA', 'MENJUAL JASA'), ('MENJUAL PRODUK', 'MENJUAL PRODUK')], max_length=255)),
            ],
        ),
    ]
